# Ex. 8.6 City names
# Create a function called city_country() that takes the name of the city and the country in which it lies. The
# function's return value should be a text string formatted as follows:
# Santiago, Chile
# Call the prepared function with at least three city-country pairs and display the value generated by them.

def city_country(city, country):
    """Returns the name of the city and country where it is located."""
    city_in_country = f"{city}, {country}"
    return city_in_country.title()

print(city_country('rome', 'italy'))
print(city_country('warsaw', 'poland'))
print(city_country('london', 'england'))
